config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'home#index'
  
  get 'home/index'
  get '/auth/:provider/callback', to: 'sessions#callback'
  post '/auth/:provider/callback', to: 'sessions#callback'
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/home', to: 'toppages#timeline', as: :home
  post '/home/tweet', to: 'toppages#tweet', as: :tweet
  
  post '/home/analyze_10', to: 'toppages#analyze_10'
  post '/home/analyze_8', to: 'toppages#analyze_8'
  post '/home/analyze_5', to: 'toppages#analyze_5'

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :login_required, only: [:timeline, :tweet]
  include Common
  require 'twitter'
  require 'mecab'
  require 'open-uri'
  require 'net/http'
  require 'json'

  # Amazon::Ecs.configure do |options|
  #   options[:AWS_access_key_id] = ENV['AWS_access_key']
  #   options[:AWS_secret_key] = ENV['AWS_secret_key']
  #   options[:associate_tag] = ENV['AWS_associate_tag']
  # end
  #
  # Amazon::Ecs::debug = true
  #

  def tweet
    if(params[:text] == '')
      flash[:danger] = '新規Tweetが空です'
      render './layouts/_flash_messages.html.erb'
    else
      client = client_new
      client.update(params[:text])
      redirect_to home_path
    end
  end

  def timeline
    client = client_new
    @user = client.user
    @tweets = Kaminari.paginate_array(client.home_timeline(include_entities: true)).page(params[:page]).per(5)

    p @user.tweets_count
    p client.home_timeline.count
    
    # 以下竹原追記↓
    # こっちはフォローも含めたタイムラインを出力
    # @tweets.each do |tweet|
    #   p tweet.text
    # end
    
    # こっちは特定ユーザのユーザーのid元にtimeline取得、timelineidごとにステータスを取得しテキスト引っ張り出す
    @user_timeline = client.user_timeline(@user.id)
    
    parser = MeCab::NounParser.new

    @user_timeline.each do |timeline|
      p client.status(timeline.id).text
      parser << client.status(timeline.id).text
    end
    #parserにはtweetが配列で入る
    p "***parserの中身***"
    p parser
  
    nouns = parser.parse.nouns
    p "***nounsの中身***"
    p nouns

    #cookieがセッションオーバーしないように、取り出す個数を制限
    nouns_limit = []
    for i in 0..9 do
      nouns_limit << nouns[i]
    end

    @nouns = nouns_limit.map { |noun| noun[:noun] }

    session[:nouns] = @nouns

    # 10words
    @str = ''
    @nouns[0..10].each do |noun|
      noun = noun.gsub(/(@.*|http.*)/,"")
      if @str == ''
        @str = @str + noun
      else
        @str = @str + '+' + noun
       end
    end

    #8words
    @str_8 = ''
    @nouns[0..8].each do |noun|
      noun = noun.gsub(/(@.*|http.*)/,"")
      if @str_8 == ''
        @str_8 = @str_8 + noun
      else
        @str_8 = @str_8 + '+' + noun
       end
    end

    #5words
    @str_5 = ''
    @nouns[0..5].each do |noun|
      noun = noun.gsub(/(@.*|http.*)/,"")
      if @str_5 == ''
        @str_5 = @str_5 + noun
      else
        @str_5 = @str_5 + '+' + noun
       end
    end
    
    session[:str_10] = @str
    session[:str_8] = @str_8
    session[:str_5] = @str_5
    
    p "***session[:str_10]の中身***"
    p session[:str_10]
    p "------------------"
    p "***session[:str_8]の中身***"
    p session[:str_8]
    p "------------------"
    p "***session[:str_5]の中身***"
    p session[:str_5]
    
  end
  
  def client_new
    Twitter::REST::Client.new do |config|
      p "***client_newの中身***"
      p config.consumer_key = ENV["TWITTER_CONSUMER_KEY"]
      p config.consumer_secret = ENV["TWITTER_CONSUMER_SECRET"]
      p config.access_token = session[:oauth_token]
      p config.access_token_secret = session[:oauth_token_secret]
    end
  end
  
  #10words
  def analyze_10
   
    base_url = 'https://www.googleapis.com/books/v1/volumes?q='
    keyword_10 = session[:str_10]
    url = URI.parse(URI.encode(base_url + keyword_10))
    p "URI結果" + url.to_s
    result = Net::HTTP.get_response(url)
    p result.to_s
    json = JSON.parse(result.body)

    unless json['items'] == nil

      @datas = []
      json['items'].each do |item|

        #著者
        if item['volumeInfo'].has_key?('authors')
          authors_name = item['volumeInfo']['authors'][0]
        elsif item['volumeInfo'].has_key?('publisher')
          authors_name = item['volumeInfo']['publisher']
        else
          authors_name = '不明'
        end

        #タイトル
        if item['volumeInfo'].has_key?('title')
          title_name = item['volumeInfo']['title']
        else
          titile_name = '不明'
        end

        #リンク先
        if item['volumeInfo'].has_key?('infoLink')
          info_name = item['volumeInfo']['infoLink']
        else
          info_name = nil
        end

        #識別番号
        if item['volumeInfo'].has_key?('industryIdentifiers')
          code_name = item['volumeInfo']['industryIdentifiers'][0]['identifier']
        else
          code_name = '不明'
        end

        #サムネイル
        if item['volumeInfo'].has_key?('imageLinks')
          thumbnail_name = item['volumeInfo']['imageLinks']['thumbnail']
        else
          thumbnail_name = "NO IMAGE"
        end

        #説明
        if item['volumeInfo'].has_key?('description')
          description_name = item['volumeInfo']['description']
        else
          description_name = '説明はありません'
        end
        data = {
            code: code_name,
            title: title_name,
            info: info_name,
            authors: authors_name,
            thumbnail: thumbnail_name,
            description: description_name
        }

        p "***dataの情報***"
        p data
        @datas << data
      end

    else
      render 'analyze_10'
    end

  end
  
  #8words
  def analyze_8
    
    base_url = 'https://www.googleapis.com/books/v1/volumes?q='
    keyword_8 = session[:str_10]
    url = URI.parse(URI.encode(base_url + keyword_8))
    p "URI結果" + url.to_s
    result = Net::HTTP.get_response(url)
    p result.to_s
    json = JSON.parse(result.body)
    
    unless json['items'] == nil
    
      @datas = []
      json['items'].each do |item|
        
        #著者
        if item['volumeInfo'].has_key?('authors')
          authors_name = item['volumeInfo']['authors'][0]
        elsif item['volumeInfo'].has_key?('publisher')
          authors_name = item['volumeInfo']['publisher']
        else
          authors_name = '不明'
        end
        
        #タイトル
        if item['volumeInfo'].has_key?('title')
          title_name = item['volumeInfo']['title']
        else
          titile_name = '不明'
        end
        
        #リンク先
        if item['volumeInfo'].has_key?('infoLink')
          info_name = item['volumeInfo']['infoLink']
        else
          info_name = nil
        end
        
        #識別番号
        if item['volumeInfo'].has_key?('industryIdentifiers')
          code_name = item['volumeInfo']['industryIdentifiers'][0]['identifier']
        else
          code_name = '不明'
        end
        
        #サムネイル
        if item['volumeInfo'].has_key?('imageLinks')
          thumbnail_name = item['volumeInfo']['imageLinks']['thumbnail']
        else
          thumbnail_name = "NO IMAGE"
        end
        
        #説明
        if item['volumeInfo'].has_key?('description')
          description_name = item['volumeInfo']['description']
        else
          description_name = '説明はありません'
        end
        data = {  
            code: code_name,
            title: title_name,
            info: info_name,
            authors: authors_name,
            thumbnail: thumbnail_name,
            description: description_name
        }
        p "***dataの情報***"
        p data
        @datas << data
      end
    
    else
      render 'analyze_8'
    end
  end
  
  
  #5words
  def analyze_5
    
    base_url = 'https://www.googleapis.com/books/v1/volumes?q='
    keyword_5 = session[:str_5]
    url = URI.parse(URI.encode(base_url + keyword_5))
    p "URI結果" + url.to_s
    result = Net::HTTP.get_response(url)
    p result.to_s
    json = JSON.parse(result.body)
    
    unless json['items'] == nil
    
      @datas = []
      json['items'].each do |item|
        
        #著者
        if item['volumeInfo'].has_key?('authors')
          authors_name = item['volumeInfo']['authors'][0]
        elsif item['volumeInfo'].has_key?('publisher')
          authors_name = item['volumeInfo']['publisher']
        else
          authors_name = '不明'
        end
        
        #タイトル
        if item['volumeInfo'].has_key?('title')
          title_name = item['volumeInfo']['title']
        else
          titile_name = '不明'
        end
        
        #リンク先
        if item['volumeInfo'].has_key?('infoLink')
          info_name = item['volumeInfo']['infoLink']
        else
          info_name = nil
        end
        
        #識別番号
        if item['volumeInfo'].has_key?('industryIdentifiers')
          code_name = item['volumeInfo']['industryIdentifiers'][0]['identifier']
        else
          code_name = '不明'
        end
        
        #サムネイル
        if item['volumeInfo'].has_key?('imageLinks')
          thumbnail_name = item['volumeInfo']['imageLinks']['thumbnail']
        else
          thumbnail_name = "NO IMAGE"
        end
        
        #説明
        if item['volumeInfo'].has_key?('description')
          description_name = item['volumeInfo']['description']
        else
          description_name = '説明はありません'
        end
        data = {  
            code: code_name,
            title: title_name,
            info: info_name,
            authors: authors_name,
            thumbnail: thumbnail_name,
            description: description_name
        }
        p "***dataの情報***"
        p data
        @datas << data
      end
    
    else
      render 'analyze_5'
    end
  end
end

app/views/toppages/analyze_10.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Bookpack</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
      <h1 class="recommend">アナタにオススメの本</h1>
      <div class="back">
          <%= link_to '前に戻る' ,home_path , class: 'btn btn-default'%>
      </div>
      <div class="index-content">
      <div class="container">
            <% unless @datas == nil%>
                  <% @datas.each do |data|%>
                  <div class="col-md-3 col-sm-4 col-xs-12 panel-out">
                  <div class="panel panel-default">
                        <div class="panel-heading text-center parent">
                          <% unless data[:thumbnail] == "NO IMAGE"%>
                            <img src="<%= data[:thumbnail]%>" alt="" class="card-img-top">
                          <% else %>
                            <img src="/noimage.png" alt="" class="card-img-top">
                          <% end%>
                        </div>
                        
                        <div class="panel-body">
                            <p class="item-title"><%= link_to data[:title], data[:info], target: '_blank' %></p>
                            <p class="item-title">著者: <%= data[:authors]%></p>
                            <p class="item-title">内容: <%= data[:description]%></p>
                        </div>
                  </div>
                  </div>
                  <% end %>
             <% else %>
                 <h1 class="recommend">オススメの本が見つかりませんでした・・・</h1>
                 <h2 class="recommend">他のボタンをお試しください！</h2>
             <% end %>
      </div>
      </div>
      
</body>
</html>

app/views/toppages/analyze_5.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Bookpack</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
      <h1 class="recommend">アナタにオススメの本</h1>
      <div class="back">
          <%= link_to '前に戻る' ,home_path , class: 'btn btn-default'%>
      </div>
      <div class="index-content">
      <div class="container">
            <% unless @datas == nil%>
                  <% @datas.each do |data|%>
                  <div class="col-md-3 col-sm-4 col-xs-12 panel-out">
                  <div class="panel panel-default">
                        <div class="panel-heading text-center parent">
                          <% unless data[:thumbnail] == "NO IMAGE"%>
                            <img src="<%= data[:thumbnail]%>" alt="" class="card-img-top">
                          <% else %>
                            <img src="/noimage.png" alt="">
                          <% end%>
                        </div>
                        
                        <div class="panel-body">
                            <p class="item-title"><%= link_to data[:title], data[:info], target: '_blank' %></p>
                            <p class="item-title">著者: <%= data[:authors]%></p>
                            <p class="item-title">内容: <%= data[:description]%></p> 
                        </div>
                  </div>
                  </div>
                  <% end %>
             <% else %>
                 <h1 class="recommend">オススメの本が見つかりませんでした・・・</h1>
                 <h2 class="recommend">他のボタンをお試しください！</h2>
             <% end %>
      </div>
      </div>
      
</body>
</html>

app/views/toppages/analyze_8.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Bookpack</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
</head>
<body>
      <h1 class="recommend">アナタにオススメの本</h1>
      <div class="back">
          <%= link_to '前に戻る' ,home_path , class: 'btn btn-default'%>
      </div>
      <div class="index-content">
      <div class="container">
            <% unless @datas == nil%>
                  <% @datas.each do |data|%>
                  <div class="col-md-3 col-sm-4 col-xs-12 panel-out">
                  <div class="panel panel-default">
                        <div class="panel-heading text-center parent">
                          <% unless data[:thumbnail] == "NO IMAGE"%>
                            <img src="<%= data[:thumbnail]%>" alt="" class="card-img-top">
                          <% else %>
                            <img src="/noimage.png" alt="">
                          <% end%>
                        </div>
                        
                        <div class="panel-body">
                            <p class="item-title"><%= link_to data[:title], data[:info], target: '_blank' %></p>
                            <p class="item-title">著者: <%= data[:authors]%></p>
                            <p class="item-title">内容: <%= data[:description]%></p> 
                        </div>
                  </div>
                  </div>
                  <% end %>
             <% else %>
                 <h1 class="recommend">オススメの本が見つかりませんでした・・・</h1>
                 <h2 class="recommend">他のボタンをお試しください！</h2>
             <% end %>
      </div>
      </div>
      
</body>
</html>

app/views/toppages/timeline.html.erb
<!-- app/views/top/timeline.html.erb -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Bookpack</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    
  </head>
  <body>
    <div class="col-md-3 container sidebar well well-sm">
        <% if @user.profile_banner_uri_https.present? %>
          <%= image_tag(@user.profile_banner_uri_https, class: "img-responsive") %>
          <%= image_tag(@user.profile_image_uri_https('original'), class: "profile-image") %> プロフィール編集<br>
        <% end %>
        <%= @user.name %><br>
        @<%= @user.screen_name %><br>
        <div>
          <span class="col-xs-4">
            ツイート
            <span><%= @user.tweets_count %></span>
          </span>
          <div class="col-xs-4">
            フォロー
            <span><%= @user.friends_count %></span>
          </div>
          <div class="col-xs-4">
            フォロワー
            <span><%= @user.followers_count %></span>
          </div>
        </div><br>
        <%= @user.description %><br>
        <%= @user.location %><br>
        <%= @user.website %><br>
        
        <%= form_tag(tweet_path, method: "post") do %>
          <%= text_field_tag :text, '', class: "form-control input-area" %>
          <%= button_tag sanitize('<i class="fab fa-twitter"></i>  Tweetする'), :type => "submit", :class =>"tweet"%>

        <% end %>
        <span><%= form_tag(home_analyze_10_path, method: "post") do%>
          <%= button_tag sanitize('<i class="fas fa-book-open"></i> オススメの本をみてみる(10words)'), :type => "submit", :class =>"book"%>
        <% end %></span>
        
        <span><%= form_tag(home_analyze_8_path, method: "post") do%>
          <%= button_tag sanitize('<i class="fas fa-book-open"></i> オススメの本(8words)'), :type => "submit", :class =>"book"%>
        <% end %></span>
        
        <span><%= form_tag(home_analyze_5_path, method: "post") do%>
          <%= button_tag sanitize('<i class="fas fa-book-open"></i> オススメの本(5words)'), :type => "submit", :class =>"book"%>
        <% end %></span>
    </div>
      <div class="col-md-9">
        <% @tweets.each do |tweet| %>
          <div class="post-panel well well-sm">
            <div class="tweet-image">
              <%= link_to image_tag(tweet.user.profile_image_url_https) %>
            </div>
            <div class="post">
              <%= tweet.user.name %> @<%= tweet.user.screen_name %><br />
              <%= tweet.text %><br />
              RT <%= tweet.retweet_count %> いいね <%= tweet.favorite_count %><br />
              <%= tweet.created_at %><br />
              <div class="post-image">
                <% if tweet.media? %>
                  <% tweet.media.each do |media| %>
                    <%= image_tag(media.media_url_https) %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
        <%= paginate @tweets %>
      </div>
  </body>
</html>