config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'home#index'
  
  get 'home/index'
  get '/auth/:provider/callback', to: 'sessions#callback'
  post '/auth/:provider/callback', to: 'sessions#callback'
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/home', to: 'toppages#timeline', as: :home
  post '/home/tweet', to: 'toppages#tweet', as: :tweet
  
  post '/home/analyze_10', to: 'toppages#analyze_10'
  post '/home/analyze_8', to: 'toppages#analyze_8'
  post '/home/analyze_5', to: 'toppages#analyze_5'

end

app/views/layouts/_flash_messages.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Bookpack</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="container">
            <% flash.each do |message_type, message| %>
                <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <div class="back">
              <%= link_to '前に戻る' ,home_path , class: 'btn btn-default'%>
            </div>
        </div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookpack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c" rel="stylesheet">

  </head>

  <body>
  
    <header>
      <!--  <nav class="navbar navbar-inverse navbar-static-top">-->
      <!--    <div class="container">-->
      <!--      <div class="navbar-header">-->
      <!--        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">-->
      <!--          <span class="sr-only">Toggle navigation</span>-->
      <!--          <span class="icon-bar"></span>-->
      <!--          <span class="icon-bar"></span>-->
      <!--          <span class="icon-bar"></span>-->
      <!--        </button>-->
      <!--        <a class="navbar-brand" href="/">Bookpack</a>-->
      <!--      </div>-->
      <!--      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">-->
      <!--        <ul class="nav navbar-nav navbar-right">-->
      <%# if current_user %>
      <!--               <li><%#= link_to 'ログアウト', logout_path %></li>-->
      <%# else %>
      <!--               <li><%#= link_to 'ログイン', '/auth/twitter' %></li>-->
      <%# end %>
      <!--        </ul>-->
      <!--      </div>-->
      <!--    </div>-->
<!--      </nav>-->

      <script src="https://unpkg.com/vue-navigation-bar@1.0.0/dist/vue-navigation-bar.min.js"></script>

      <link rel="stylesheet" type="text/css" href="https://unpkg.com/vue-navigation-bar@1.0.0/dist/vue-navigation-bar.css">
      <script src="https://unpkg.com/tippy.js/dist/tippy.all.min.js"></script>
</header>
    <div id="app">
      <%= javascript_pack_tag 'hello_vue' %>
    </div>
    <%= yield %>
  </body>
</html>